package main

type Vec2_32 = [2]float32
type Vec2 = [2]float64
type Vec2_i = [2]int

const (
	SCREEN_WIDTH    = 640
	SCREEN_HEIGHT   = 480
	HALF_HEIGHT     = SCREEN_HEIGHT / 2
	HALF_WIDTH      = SCREEN_WIDTH / 2
	PLAYER_FRICTION = 0.5
	PLAYER_ACCEL    = 0.5 + PLAYER_FRICTION
	MAX_SPEED       = 2.0
	JMP_SPEED       = 10.0

	TILE_SIZE = 16

	JUMP_HEIGHT       = 50.0
	JUMP_BOOST_HEIGHT = 55.0
	FALL_VELOCITY     = 900.0
	GRAVITY           = 0.75

	TOWER_BOUNDS = 608
	TOWER_OFFSET = 240
	TOWER_WIDTH  = 192
	WORLD_WIDTH  = TOWER_BOUNDS + (TOWER_OFFSET * 2)
	WORLD_HEIGTH = SCREEN_HEIGHT * 2
)
